// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRealm = "realm"

// Realm mapped from table <realm>
type Realm struct {
	ID        int64          `gorm:"column:id;not null" json:"id"`
	Domain    string         `gorm:"column:domain;not null" json:"domain"`
	Pwdd      string         `gorm:"column:pwdd;not null" json:"pwdd"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Realm's table name
func (*Realm) TableName() string {
	return TableNameRealm
}
