# - Find MEDFILE
# Find the MEDFile includes and library
# MEDFILE_ROOT_DIR - ROOT of MEDFile library
# MEDFILE_INCLUDE_DIRS - where to find med.h
# MEDFILE_LIBRARIES - List of libraries when using MEDFile
# MEDFILE_FOUND - True if MEDFile found

# Detect headers directory
FIND_PATH(MEDFILE_INCLUDE_DIRS med.h HINTS ${MEDFILE_ROOT_DIR}/include)
# --

# Detect libraries
SET(MEDFILE_LIBRARIES)
SET(MEDFILE_C_LIBRARIES)
SET(MEDFILE_EXTRA_LIBRARIES)

FIND_LIBRARY(MEDFILE_LIBRARY_medC NAMES medC HINTS ${MEDFILE_ROOT_DIR}/lib)
IF (MEDFILE_LIBRARY_medC)
    LIST(APPEND MEDFILE_C_LIBRARIES "${MEDFILE_LIBRARY_medC}")
    LIST(APPEND MEDFILE_LIBRARIES "${MEDFILE_LIBRARY_medC}")
ENDIF ()

FIND_LIBRARY(MEDFILE_LIBRARY_medfwrap NAMES medfwrap HINTS ${MEDFILE_ROOT_DIR}/lib)
IF (MEDFILE_LIBRARY_medfwrap)
    LIST(APPEND MEDFILE_C_LIBRARIES "${MEDFILE_LIBRARY_medfwrap}")
    LIST(APPEND MEDFILE_LIBRARIES "${MEDFILE_LIBRARY_medfwrap}")
ENDIF ()

FIND_LIBRARY(MEDFILE_LIBRARY_med NAMES med HINTS ${MEDFILE_ROOT_DIR}/lib)
IF (MEDFILE_LIBRARY_med)
    LIST(APPEND MEDFILE_LIBRARIES "${MEDFILE_LIBRARY_med}")
ENDIF ()

FIND_LIBRARY(MEDFILE_LIBRARY_medimport NAMES medimport HINTS ${MEDFILE_ROOT_DIR}/lib)
IF (MEDFILE_LIBRARY_medimport)
    LIST(APPEND MEDFILE_EXTRA_LIBRARIES "${MEDFILE_LIBRARY_medimport}")
ENDIF ()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(${MEDFile_DirName} REQUIRED_VARS MEDFILE_INCLUDE_DIRS MEDFILE_LIBRARIES)

if (MEDFile_FOUND)
    find_package(MEDFile NO_MODULE)

    mark_as_advanced(MEDFILE_LIBRARIES MEDFILE_INCLUDE_DIRS)
ENDIF ()


