# - Find MEDFileIO
# Find the MEDFileIO includes and library
# MEDFILEIO_ROOT_DIR - ROOT of MEDFileIO library
# MEDFILEIO_INCLUDE_DIRS - where to find vtkMEDReader.h
# MEDFILEIO_LIBRARIES - List of libraries when using MEDFileIO.
# MEDFILEIO_FOUND - True if MEDFileIO found.

find_path(MEDFILEIO_INCLUDE_DIRS
        NAMES vtkMEDReader.h
        HINTS ${MEDFILEIO_ROOT_DIR}/include)

SET(MEDFILEIO_LIBRARIES "")

FIND_LIBRARY(MEDFILEIO_LIBRARY_MEDLoaderForPV NAMES MEDLoaderForPV HINTS ${MEDFILEIO_ROOT_DIR}/lib)
IF (MEDFILEIO_LIBRARY_MEDLoaderForPV)
    LIST(APPEND MEDFILEIO_LIBRARIES "${MEDFILEIO_LIBRARY_MEDLoaderForPV}")
ENDIF ()

FIND_LIBRARY(MEDFILEIO_LIBRARY_MEDReaderIO NAMES MEDReaderIO HINTS ${MEDFILEIO_ROOT_DIR}/lib)
IF (MEDFILEIO_LIBRARY_MEDReaderIO)
    LIST(APPEND MEDFILEIO_LIBRARIES "${MEDFILEIO_LIBRARY_MEDReaderIO}")
ENDIF ()

FIND_LIBRARY(MEDFILEIO_LIBRARY_MEDWriterIO NAMES MEDWriterIO HINTS ${MEDFILEIO_ROOT_DIR}/lib)
IF (MEDFILEIO_LIBRARY_MEDWriterIO)
    LIST(APPEND MEDFILEIO_LIBRARIES "${MEDFILEIO_LIBRARY_MEDWriterIO}")
ENDIF ()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MEDFileIO DEFAULT_MSG MEDFILEIO_LIBRARY_MEDLoaderForPV MEDFILEIO_LIBRARY_MEDReaderIO MEDFILEIO_LIBRARY_MEDWriterIO
        MEDFILEIO_INCLUDE_DIRS)

if(MEDFileIO_FOUND)
    find_package(MEDFileIO NO_MODULE)
    mark_as_advanced(MEDFILEIO_LIBRARIES MEDFILEIO_INCLUDE_DIRS)
else()
    set(MEDFileIO_FOUND FALSE)
ENDIF ()

# if (MEDFILEIO_LIBRARY_MEDLoaderForPV AND MEDFILEIO_LIBRARY_MEDReaderIO AND MEDFILEIO_LIBRARY_MEDWriterIO)
#     set(MEDFILEIO_LIBRARIES MEDLoaderForPV MEDReaderIO MEDWriterIO)
#     set(MEDFILEIO_LIBS_DIR ${MEDFILEIO_ROOT_DIR}/lib)
#     set(MEDFileIO_FOUND TURE)
# endif ()