set(CompileCPUMax_MakeCommand make -j${CPU_CORES})

# ---[ Threads
set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
set(THREADS_PREFER_PTHREAD_FLAG TRUE)
find_package(Threads REQUIRED)
list(APPEND PROJECT_LINKER_LIBS ${CMAKE_THREAD_LIBS_INIT})


# ---[ VTK
set(VTK_DirName "VTK")
include(${CMAKE_EXTERNAL_PATH}/VTK.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${VTK_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${VTK_LIBRARIES})
