set(CompileCPUMax_MakeCommand make -j${CPU_CORES})

if (BUILD_WITH_STATIC)
    set(LIBRARY_PREFIX ${CMAKE_STATIC_LIBRARY_PREFIX})
    set(LIBRARY_SUFFIX ${CMAKE_STATIC_LIBRARY_SUFFIX})
else ()
    set(LIBRARY_PREFIX ${CMAKE_SHARED_LIBRARY_PREFIX})
    set(LIBRARY_SUFFIX ${CMAKE_SHARED_LIBRARY_SUFFIX})
endif ()


# ---[ Threads
set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
set(THREADS_PREFER_PTHREAD_FLAG TRUE)
find_package(Threads REQUIRED)
list(APPEND PROJECT_LINKER_LIBS ${CMAKE_THREAD_LIBS_INIT})

# ---[ ZLib
set(ZLib_DirName "ZLib")
include(${CMAKE_EXTERNAL_PATH}/ZLib.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${ZLIB_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${ZLIB_LIBRARIES})

# ---[ OpenMPI
set(OpenMPI_DirName "OpenMPI")
include(${CMAKE_EXTERNAL_PATH}/OpenMPI.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${MPI_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${MPI_LIBRARIES})


# ---[ HDF5
set(HDF5_DirName "HDF5")
include(${CMAKE_EXTERNAL_PATH}/HDF5.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${HDF5_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${HDF5_LIBRARIES})
list(APPEND PROJECT_LINKER_DIRS ${HDF5_LIBS_DIR})

# ---[ ParaView
set(ParaView_DirName "ParaView")
include(${CMAKE_EXTERNAL_PATH}/ParaView.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${PARAVIEW_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${PARAVIEW_LIBRARIES})
list(APPEND PROJECT_LINKER_DIRS ${PARAVIEW_LIBS_DIR})

list(APPEND PROJECT_INCLUDE_DIRS ${VTK_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${VTK_LIBRARIES})

# ---[ MEDFile
set(MEDFile_DirName "MEDFile")
include(${CMAKE_EXTERNAL_PATH}/MEDFile.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${MEDFILE_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${MEDFILE_LIBRARIES})
list(APPEND PROJECT_LINKER_DIRS ${MEDFILE_LIBS_DIR})

# ---[ MEDCoupling
set(MEDCoupling_DirName "MEDCoupling")
include(${CMAKE_EXTERNAL_PATH}/MEDCoupling.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${MEDCOUPLING_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${MEDCOUPLING_LIBRARIES})
list(APPEND PROJECT_LINKER_DIRS ${MEDCOUPLING_LIBS_DIR})

# ---[ MEDFileIO
set(MEDFileIO_DirName "MEDFileIO")
include(${CMAKE_EXTERNAL_PATH}/MEDFileIO.cmake)
list(APPEND PROJECT_INCLUDE_DIRS ${MEDFILEIO_INCLUDE_DIRS})
list(APPEND PROJECT_LINKER_LIBS ${MEDFILEIO_LIBRARIES})
list(APPEND PROJECT_LINKER_DIRS ${MEDFILEIO_LIBS_DIR})

ADD_DEFINITIONS(-DMEDREADER_USE_MPI)

